import dotenv from 'dotenv';

// Load .env
dotenv.config();

export const {
  PORT,
  JWT_SECRET,
  JWT_EXPIRATION_MINUTES,
  JWT_BEARER,
  JWT_REFRESH_TIME,
  JWT_REFRESH_TYPE,
  DBURL,
  API_BASE_URI,
  NODE_ENV,
  REDIS_URL,
  HOST,

  LOGS_DBURL,
  // CLOUDWATCH_GROUP_NAME,
  // CLOUDWATCH_GROUP_STREAM,
  // CLOUDWATCH_ACCESS_KEY,
  // CLOUDWATCH_SECRET_ACCESS_KEY,
  // CLOUDWATCH_REGION,
  // NODE_ENV_CLOUDWATCH,

  // ACCESS_AWS_KEY_ID,
  // SECRET_AWS_ACCESS_KEY,
  // BUCKET_AWS_REGION,
  // SES_AWS_CONFIG_SET,
  // MAILER_FROM_OPTION,
  // LOGS_MAIL,

  GMAIL_EMAIL,
  GMAIL_CLIENT_ID,
  GMAIL_CLIENT_SECRET,
  GMAIL_REFRESH_TOKEN,
  SENDER_EMAIL,
  CLIENT_HOST,

  TERMI_BASE_URL,
  TERMI_API_KEY,

  // BULK_SMS_NG_URL,
	// BULK_SMS_USERNAME,
	// BULK_SMS_PASS,
	// BULK_SMS_SENDER,

  // SMART_SMS_TOKEN,
  // SMART_SMS_URL
  PENPAY_BASE_URL,
  PENPAY_API_KEY
} = process.env;
